---
- name: Install Anaconda3 {{ item.version_number }}
  vars:
    anaconda_dir: "{{ common_dir }}/anaconda3"
    anaconda_module_dir: "{{ common_modules }}/anaconda3"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ anaconda_dir }}/{{ version_number }}"
    anaconda_url: "{{ item.url }}"
  tags:
    - never
    - anaconda3-{{ item.version_number }}

  block:
    - name: Download, and install Anaconda {{ version_number }}
      block:
        - name: Download Anaconda {{ version_number }} from {{ anaconda_url }}
          ansible.builtin.get_url:
            url: "{{ anaconda_url }}"
            dest: "{{ common_src }}/Anaconda3-{{ version_number }}.sh"
            checksum: "{{ checksum }}"
            mode: u=rx,g=r,o=r
        - name: Run Anaconda {{ version_number }} installer – {{ install_dir }}
          ansible.builtin.command: "/usr/bin/bash {{ common_src }}/Anaconda3-{{ version_number }}.sh -b -f -p {{ install_dir }}"
          args:
            creates: "{{ install_dir }}"
        - name: Install conda packages
          ansible.builtin.command: "{{ install_dir }}/bin/conda install --force-reinstall coloredlogs configparser pandas"
          args:
            creates: "{{ install_dir }}/pkgs/pandas*"
        - name: Install Jupyter
          ansible.builtin.command: "{{ install_dir }}/bin/conda install -c conda-forge jupyterlab"
          args:
            creates: "{{ install_dir }}/pkgs/jupyter*"
        - name: Add condarc
          ansible.builtin.template:
            src: anaconda.rc
            dest: "{{ install_dir }}/condarc"
            mode: u=rw,g=r,o=r

    - name: Install Anaconda {{ version_number }} module to {{ anaconda_module_dir }}
      block:
        - name: Check module dir {{ anaconda_module_dir }}
          ansible.builtin.file:
            path: "{{ anaconda_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install Anaconda module file to {{ anaconda_module_dir }}/{{ version_number }}.lua
          ansible.builtin.template:
            src: anaconda.lua
            dest: "{{ anaconda_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
