- name: Install fribidi
  vars:
    fribidi_dir: "{{ common_dir }}/fribidi"
    fribidi_module_dir: "{{ common_modules }}/fribidi"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ fribidi_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/fribidi-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - fribidi{{ item.version_number }}
  environment:
    MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
  block:
    - name: Download fribidi {{ version_number }}
      get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/fribidi-{{ version_number }}.tar.xz"
        checksum: "{{ checksum }}"
    - name: Unzip fribidi {{ version_number }}
      unarchive:
        src: "{{ common_src }}/fribidi-{{ version_number }}.tar.xz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Make fribidi {{ version_number }} build directory {{ build_dir }}
      file:
        path: "{{ build_dir }}"
        state: directory
    - name: Run fribidi {{ version_number }} configure
      command: "../configure --prefix={{ install_dir }}"
      args:
        chdir: "{{ build_dir }}"
        creates: "{{ build_dir }}/Makefile"
    - name: Build fribidi {{ version_number }}
      make:
        chdir: "{{ build_dir }}"

    - name: Install fribidi {{ version_number }}
      make:
        chdir: "{{ build_dir }}"
        target: install

    - name: Install fribidi {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ fribidi_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install fribidi module file
          template:
            src: common/fribidi.lua
            dest: "{{ fribidi_module_dir }}/{{ version_number }}.lua"
