---
- name: Install fzf {{ item.version_number }}
  vars:
    fzf_dir: "{{ common_dir }}/fzf"
    fzf_module_dir: "{{ common_modules }}/fzf"
    repo: "{{ item.repo }}"
    version_number: "{{ item.version_number }}"
    url: "{{ item.url }}"
    source_dir: "{{ common_dir }}/src"
    install_dir: "{{ fzf_dir }}/{{ version_number }}"
  tags:
    - never
    - fzf{{ item.version_number }}

  block:
    - name: Download and install fzf ({{ version_number }})
      block:
        - name: Download fzf {{ version_number }} from {{ repo }}
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ source_dir }}/fzf-{{ version_number }}.tar.gz"
            mode: u=rw,g=r,o=r
        - name: Ensure fzf dir exists
          ansible.builtin.file:
            path: "{{ install_dir }}"
            state: directory
            recurse: true
        - name: Extract fzf {{ version_number }}
          ansible.builtin.unarchive:
            src: "{{ source_dir }}/fzf-{{ version_number }}.tar.gz"
            dest: "{{ install_dir }}"
            remote_src: true
            creates: "{{ install_dir }}/fzf"

    - name: Install fzf module {{ version_number }}
      block:
        - name: Check module dir {{ fzf_module_dir }}
          ansible.builtin.file:
            path: "{{ fzf_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install fzf module file {{ version_number }}
          ansible.builtin.template:
            src: fzf.lua
            dest: "{{ fzf_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
