- name: Install gettext
  vars:
    gettext_dir: "{{ common_dir }}/gettext"
    gettext_module_dir: "{{ common_modules }}/gettext"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ gettext_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/gettext-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - gettext{{ item.version_number }}
  block:
    - name: Install gettext {{ version_number }}
      block:
        - name: Download, compile and install gettext {{ version_number }}
          block:
            - name: Download gettext {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/gettext-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip gettext {{ version_number }}
              unarchive:
                src: "{{ common_src }}/gettext-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Make gettext {{ version_number }} build directory {{ build_dir }}
              file:
                path: "{{ build_dir }}"
                state: directory
            - name: Run gettext {{ version_number }} configure
              command: "../configure --prefix={{ install_dir }}"
              args:
                chdir: "{{ build_dir }}"
                creates: "{{ build_dir }}/Makefile"
            - name: Build gettext {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
              environment:
                MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
            - name: Install gettext {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
                target: install

    - name: Install gettext {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ gettext_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install gettext module file
          template:
            src: common/gettext.lua
            dest: "{{ gettext_module_dir }}/{{ version_number }}.lua"
