- name: Install git-lfs
  vars:
    git_lfs_dir: "{{ common_dir }}/git-lfs"
    git_lfs_module_dir: "{{ common_modules }}/git-lfs"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ git_lfs_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/git-lfs-{{ version_number }}"
  tags:
    - never
    - git-lfs{{ item.version_number }}
  block:
    - name: check if git-lfs is already installed
      stat:
        path: "{{ install_dir }}"
      register: git_lfs_installed
    - name: Download git-lfs {{ version_number }}
      when: not git_lfs_installed.stat.exists
      get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/git-lfs-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
    - name: Unzip git-lfs {{ version_number }}
      when: not git_lfs_installed.stat.exists
      unarchive:
        src: "{{ common_src }}/git-lfs-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Ensure git-lfs dir "{{ git_lfs_dir }}" exists
      when: not git_lfs_installed.stat.exists
      file:
        path: "{{ git_lfs_dir }}"
        state: directory
    - name: Move uncompressed git-lfs {{ version_number }} to install dir
      when: not git_lfs_installed.stat.exists
      command: mv "{{ unzipdir }}" "{{ install_dir }}"

    - name: Check module dir
      file:
        path: "{{ git_lfs_module_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Install git-lfs module file
      template:
        src: common/git-lfs.lua
        dest: "{{ git_lfs_module_dir }}/{{ version_number }}.lua"
