---
- name: Install git-lfs
  vars:
    git_lfs_dir: "{{ common_dir }}/git-lfs"
    git_lfs_module_dir: "{{ common_modules }}/git-lfs"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ git_lfs_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/git-lfs-{{ version_number }}"
  tags:
    - never
    - git-lfs{{ item.version_number }}
  block:
    - name: Check if git-lfs is already installed
      ansible.builtin.stat:
        path: "{{ install_dir }}"
      register: git_lfs_installed
    - name: Download git-lfs {{ version_number }}
      when: not git_lfs_installed.stat.exists
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/git-lfs-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
        mode: u=rw,g=r,o=r
    - name: Unzip git-lfs {{ version_number }}
      when: not git_lfs_installed.stat.exists
      ansible.builtin.unarchive:
        src: "{{ common_src }}/git-lfs-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Ensure git-lfs dir " " exists {{ git_lfs_dir }}
      when: not git_lfs_installed.stat.exists
      ansible.builtin.file:
        path: "{{ git_lfs_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Move uncompressed git-lfs to install dir {{ version_number }}
      when: not git_lfs_installed.stat.exists
      ansible.builtin.command: mv "{{ unzipdir }}" "{{ install_dir }}"
    - name: Check module dir
      ansible.builtin.file:
        path: "{{ git_lfs_module_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Install git-lfs module file
      ansible.builtin.template:
        src: common/git-lfs.lua
        dest: "{{ git_lfs_module_dir }}/{{ version_number }}.lua"
        mode: u=rw,g=r,o=r
