---
- name: Install git
  vars:
    git_dir: "{{ common_dir }}/git"
    git_module_dir: "{{ common_modules }}/git"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ git_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/git-{{ version_number }}"
    build_dir: "{{ unzipdir }}"
    gettext_dir: "{{ item.gettext_dir }}"
    gettext_module: "{{ item.gettext_module }}"
  environment:
    PATH: "{{ gettext_dir }}/bin:{{ ansible_facts['env'].PATH }}"
    LD_LIBRARY_PATH: "{{ gettext_dir }}/lib{% if 'LD_LIBRARY_PATH' in ansible_facts['env'] %}:{{ ansible_facts['env'].LD_LIBRARY_PATH }}{% endif %}"
    INCLUDE: "{{ gettext_dir }}/include{% if 'INCLUDE' in ansible_facts['env'] %}:{{ ansible_facts['env'].INCLUDE }}{% endif %}"
    MAKEFLAGS: "-j {{ ansible_facts['processor_vcpus'] }}"
  tags:
    - never
    - git{{ item.version_number }}
  block:
    - name: Install git {{ version_number }}
      block:
        - name: Download, compile and install git {{ version_number }}
          block:
            - name: Download git {{ version_number }}
              ansible.builtin.get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/git-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
                mode: u=rw,g=r,o=r
            - name: Unzip git {{ version_number }}
              ansible.builtin.unarchive:
                src: "{{ common_src }}/git-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Remove old configure
              ansible.builtin.file:
                path: "{{ build_dir }}/configure"
                state: absent
            - name: Run make configure
              ansible.builtin.command: "make configure"
              args:
                chdir: "{{ build_dir }}"
                creates: "{{ build_dir }}/configure"
            - name: Run git configure {{ version_number }}
              ansible.builtin.command: "./configure --prefix={{ install_dir }}"
              args:
                chdir: "{{ build_dir }}"
            - name: Make all
              community.general.make:
                chdir: "{{ build_dir }}"
                target: all
                params:
                  prefix: "{{ install_dir }}"
            - name: Install git {{ version_number }}
              community.general.make:
                chdir: "{{ build_dir }}"
                target: install
                params:
                  prefix: "{{ install_dir }}"

    - name: Install git module {{ version_number }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ git_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install git module file
          ansible.builtin.template:
            src: common/git.lua
            dest: "{{ git_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
