- name: Install git
  vars:
    git_dir: "{{ common_dir }}/git"
    git_module_dir: "{{ common_modules }}/git"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ git_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/git-{{ version_number }}"
    build_dir: "{{ unzipdir }}"
    gettext_dir: "{{ item.gettext_dir }}"
    gettext_module: "{{ item.gettext_module }}"
  environment:
    PATH: "{{ gettext_dir }}/bin:{{ ansible_env.PATH }}"
    LD_LIBRARY_PATH: "{{ gettext_dir }}/lib{% if 'LD_LIBRARY_PATH' in ansible_env %}:{{ ansible_env.LD_LIBRARY_PATH }}{% endif %}"
    INCLUDE: "{{ gettext_dir }}/include{% if 'INCLUDE' in ansible_env %}:{{ ansible_env.INCLUDE }}{% endif %}"
    MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
  tags:
    - never
    - git{{ item.version_number }}
  block:
    - name: Install git {{ version_number }}
      block:
        - name: Download, compile and install git {{ version_number }}
          block:
            - name: Download git {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/git-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip git {{ version_number }}
              unarchive:
                src: "{{ common_src }}/git-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Remove old configure
              file:
                path: "{{ build_dir }}/configure"
                state: absent
            - name: Run make configure
              command: "make configure"
              args:
                  chdir: "{{ build_dir }}"
                  creates: "{{ build_dir }}/configure"
            - name: Run git {{ version_number }} configure
              command: "./configure --prefix={{ install_dir }}"
              args:
                chdir: "{{ build_dir }}"
            - name: Make all
              make:
                chdir: "{{ build_dir }}"
                target: all
                params:
                  prefix: "{{ install_dir }}"
            - name: Install git {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
                target: install
                params:
                  prefix: "{{ install_dir }}"

    - name: Install git {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ git_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install git module file
          template:
            src: common/git.lua
            dest: "{{ git_module_dir }}/{{ version_number }}.lua"
