- name: Install Gnu Scientific Library (libgsl)
  vars:
    gsl_dir: "{{ common_dir }}/libgsl"
    gsl_module_dir: "{{ common_modules }}/libgsl"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ gsl_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/gsl-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - gsl{{ item.version_number }}
  block:
    - name: Download Gnu Scientific Library (libgsl) {{ version_number }}
      get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/gsl-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
    - name: Unzip Gnu Scientific Library (libgsl) {{ version_number }}
      unarchive:
        src: "{{ common_src }}/gsl-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Make Gnu Scientific Library (libgsl) {{ version_number }} build directory
      file:
        path: "{{ build_dir }}"
        state: directory
    - name: Run Gnu Scientific Library (libgsl) {{ version_number }} configure
      command: "../configure --prefix={{ install_dir }}"
      args:
        chdir: "{{ build_dir }}"
        creates: "{{ build_dir }}/Makefile"
    - name: Build Gnu Scientific Library (libgsl) {{ version_number }}
      make:
        chdir: "{{ build_dir }}"
      environment:
        MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
    - name: Install Gnu Scientific Library (libgsl) {{ version_number }}
      make:
        chdir: "{{ build_dir }}"
        target: install

    - name: Install Gnu Scientific Library (libgsl) {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ gsl_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install Gnu Scientific Library (libgsl) module file
          template:
            src: gsl.lua
            dest: "{{ gsl_module_dir }}/{{ version_number }}.lua"
