- name: Install harfbuzz
  vars:
    harfbuzz_dir: "{{ common_dir }}/harfbuzz"
    harfbuzz_module_dir: "{{ common_modules }}/harfbuzz"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ harfbuzz_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/harfbuzz-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - harfbuzz{{ item.version_number }}
  environment:
    MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
  block:
    - name: Download harfbuzz {{ version_number }}
      get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/harfbuzz-{{ version_number }}.tar.xz"
        checksum: "{{ checksum }}"
    - name: Unzip harfbuzz {{ version_number }}
      unarchive:
        src: "{{ common_src }}/harfbuzz-{{ version_number }}.tar.xz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Make harfbuzz {{ version_number }} build directory {{ build_dir }}
      file:
        path: "{{ build_dir }}"
        state: directory
    - name: Run harfbuzz {{ version_number }} configure
      command: "../configure --prefix={{ install_dir }}"
      args:
        chdir: "{{ build_dir }}"
        creates: "{{ build_dir }}/Makefile"
    - name: Build harfbuzz {{ version_number }}
      make:
        chdir: "{{ build_dir }}"

    - name: Install harfbuzz {{ version_number }}
      make:
        chdir: "{{ build_dir }}"
        target: install

    - name: Install harfbuzz {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ harfbuzz_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install harfbuzz module file
          template:
            src: common/harfbuzz.lua
            dest: "{{ harfbuzz_module_dir }}/{{ version_number }}.lua"
