---
- name: Install hwloc
  vars:
    hwloc_dir: "{{ common_dir }}/hwloc"
    hwloc_module_dir: "{{ common_modules }}/hwloc"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ hwloc_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/hwloc-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - hwloc{{ item.version_number }}
  block:
    - name: Install hwloc {{ version_number }}
      block:
        - name: Download, compile and install hwloc {{ version_number }}
          block:
            - name: Download hwloc {{ version_number }}
              ansible.builtin.get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/hwloc-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
                mode: u=rw,g=r,o=r
            - name: Unzip hwloc {{ version_number }}
              ansible.builtin.unarchive:
                src: "{{ common_src }}/hwloc-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Make hwloc {{ version_number }} build directory {{ build_dir }}
              ansible.builtin.file:
                path: "{{ build_dir }}"
                state: directory
                mode: u=rwx,g=rwx,o=rx
            - name: Run hwloc configure {{ version_number }}
              ansible.builtin.command: "../configure --prefix={{ install_dir }}"
              args:
                chdir: "{{ build_dir }}"
                creates: "{{ build_dir }}/Makefile"
            - name: Build hwloc {{ version_number }}
              community.general.make:
                chdir: "{{ build_dir }}"
              environment:
                MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
            - name: Install hwloc {{ version_number }}
              community.general.make:
                chdir: "{{ build_dir }}"
                target: install

    - name: Install hwloc module {{ version_number }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ hwloc_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install hwloc module file
          ansible.builtin.template:
            src: hwloc.lua
            dest: "{{ hwloc_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
