---
- name: Install inteloneAPI {{ item.version_number }}
  vars:
    version: "{{ item.version_number }}"
    inteloneAPI_dir: "{{ common_dir }}/inteloneAPI"
    inteloneAPI_module_dir: "{{ common_modules }}/intel"
    install_dir: "{{ inteloneAPI_dir }}/{{ version }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    file_name: "intel_oneAPI_toolkit_{{ version }}_offline.sh"
  tags:
    - never
    - "inteloneapi{{ item.version_number }}"
  block:
    - name: Download and install inteloneAPI ({{ version }})
      block:
        - name: Download inteloneAPI installer
          get_url:
              url: "{{ url }}"
              dest: "{{ common_src }}/{{ file_name }}"
              mode: "ug=rwx,o=rx"
              checksum: "{{ checksum }}"
        - name: Run inteloneAPI installer
          command: "./{{ file_name }} -l /tmp/intel_install.{{ version }}.log -a -s --eula accept --install-dir {{ install_dir }} --action install --components default"
          args:
              chdir: "{{ common_src }}"
              creates: "{{ install_dir }}"

    - name: Install inteloneAPI modules
      command: "./modulefiles-setup.sh --output-dir={{ inteloneAPI_module_dir }}"
      args:
        chdir: "{{ install_dir }}"
