- name: Install jemalloc
  vars:
    jemalloc_dir: "{{ common_dir }}/jemalloc"
    jemalloc_module_dir: "{{ common_modules }}/jemalloc"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ jemalloc_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/jemalloc-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - jemalloc{{ item.version_number }}
  block:
    - name: Download jemalloc {{ version_number }}
      get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/jemalloc-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
    - name: Unzip jemalloc {{ version_number }}
      unarchive:
        src: "{{ common_src }}/jemalloc-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Make jemalloc {{ version_number }} build directory
      file:
        path: "{{ build_dir }}"
        state: directory
    - name: Run jemalloc {{ version_number }} configure
      command: "../configure --prefix={{ install_dir }}"
      args:
        chdir: "{{ build_dir }}"
        creates: "{{ build_dir }}/Makefile"
    - name: Build jemalloc {{ version_number }}
      make:
        chdir: "{{ build_dir }}"
      environment:
        MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
    - name: Install jemalloc {{ version_number }}
      make:
        chdir: "{{ build_dir }}"
        target: install

    - name: Install jemalloc {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ jemalloc_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install jemalloc module file
          template:
            src: jemalloc.lua
            dest: "{{ jemalloc_module_dir }}/{{ version_number }}.lua"
