---
- name: Install Java Runtime Environment {{ item.version_number }}
  vars:
    java_dir: "{{ common_dir }}/java"
    java_module_dir: "{{ common_modules }}/java"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    filename: "{{ item.filename }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ java_dir }}/jre{{ version_number }}"
  tags:
    - never
    - jre{{ item.version_number }}
  block:
    - name: Download and install JRE {{ version_number }}
      block:
        - name: Download JRE {{ version_number }} from {{ url }}
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ common_src }}/{{ filename }}"
            checksum: "{{ checksum }}"
            mode: u=rw,g=r,o=r
        - name: Ensure java dir exists
          ansible.builtin.file:
            path: "{{ java_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Uncompress OpenJDK
          ansible.builtin.unarchive:
            src: "{{ common_src }}/{{ filename }}"
            dest: "{{ java_dir }}"
            creates: "{{ install_dir }}"

    - name: Install JRE module {{ version_number }}
      block:
        - name: Check module dir {{ java_module_dir }}
          ansible.builtin.file:
            path: "{{ java_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install JRE module file {{ java_module_dir }}/jre-{{ version_number }}.lua
          ansible.builtin.template:
            src: jre.lua
            dest: "{{ java_module_dir }}/jre-{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
