---
- name: Install neovim {{ item.version_number }}
  vars:
    neovim_dir: "{{ common_dir }}/neovim"
    neovim_module_dir: "{{ common_modules }}/neovim"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ neovim_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/nvim-linux64"
  tags:
    - never
    - neovim{{ item.version_number }}

  block:
    - name: Download and install neovim {{ version_number }}
      block:
        - name: Download neovim {{ version_number }} from {{ url }}
          get_url:
            url: "{{ url }}"
            dest: "{{ common_dir }}/src/neovim-{{ version_number }}.tar.gz"
            checksum: "{{ checksum }}"
        - name: Ensure neovim dir exists
          file:
            path: "{{ neovim_dir }}"
            state: directory
        - name: Uncompress neovim to {{ unzip_dir }}
          unarchive:
            src: "{{ common_dir }}/src/neovim-{{ version_number }}.tar.gz"
            dest: "/dev/shm"
            creates: "{{ unzip_dir }}"
        - name: Move neovim to final location
          command: "mv {{ unzip_dir }} {{ install_dir }}"
          args:
            creates: "{{ install_dir }}"

    - name: Install neovim {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ neovim_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install neovim module file
          template:
            src: neovim.lua
            dest: "{{ neovim_module_dir }}/{{ version_number }}.lua"


