- name: Install OpenBLAS
  vars:
    blas_dir: "{{ common_dir }}/OpenBLAS"
    blas_module_dir: "{{ common_modules }}/openBLAS"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ blas_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/OpenBLAS-{{ version_number }}"
    build_dir: "{{ unzipdir }}"
    TARGET: "{{ item.TARGET }}"
  tags:
    - never
    - openblas{{ item.version_number }}
  block:
    - name: Install OpenBLAS {{ version_number }}
      block:
        - name: Download, compile and install OpenBLAS {{ version_number }}
          block:
            - name: Download OpenBLAS {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/openblas-v{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip OpenBLAS {{ version_number }}
              unarchive:
                src: "{{ common_src }}/openblas-v{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Build OpenBLAS {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
              environment:
                MAKEFLAGS: "-j {{ ansible_processor_count }} {{ TARGET }}"
            - name: Install OpenBLAS {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
                target: install
              environment:
                MAKEFLAGS: "PREFIX={{ install_dir }} {{ TARGET }}"

    - name: Install OpenBLAS {{ version_number }} module
      block:
        - name: Check OpenBLAS module dir
          file:
            path: "{{ blas_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install OpenBLAS {{ version_number }} module file
          template:
            src: common/openblas.lua
            dest: "{{ blas_module_dir }}/{{ version_number }}.lua"
