---
- name: Create Gnuplot container
  vars:
    checksum: "{{ item.checksum }}"
    container_name: "gnuplot"
    container_image: "{{ common_container_dir }}/{{ container_name }}.sif"
    gnuplot_module_dir: "{{ common_modules }}/gnuplot"
    gnuplot_binary_dir: "{{ common_container_dir }}/gnuplot"
  tags:
    - "gnuplot"
    - never
  block:
    - name: Create Gnuplot container {{ version_number }}
      block:
        - name: Copy singularity definition file
          ansible.builtin.template:
            src: "gnuplot.def"
            dest: "{{ common_container_recipe_dir }}/{{ container_name }}.def"
            mode: u=rw,g=r,o=r
        - name: Build singularity container
          ansible.builtin.command: "{{ singularity }} build --fakeroot {{ container_image }} {{ common_container_recipe_dir }}/{{ container_name }}.def"
          args:
            creates: "{{ container_image }}"
          environment:
            SINGULARITY_TMPDIR: "{{ lookup('env', 'SINGULARITY_TMPDIR') | default('/dev/shm', true) }}"
        - name: Ensure Gnuplot binary directory exists
          ansible.builtin.file:
            path: "{{ gnuplot_binary_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Create Gnuplot binary
          ansible.builtin.template:
            src: "gnuplot.sh"
            dest: "{{ gnuplot_binary_dir }}/gnuplot"
            mode: u=rwx,g=rx,o=rx

    - name: Install Gnuplot module {{ container_name }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ gnuplot_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install Gnuplot module file
          ansible.builtin.template:
            src: common/gnuplot.lua
            dest: "{{ gnuplot_module_dir }}/default.lua"
            mode: u=rw,g=r,o=r
