---
- name: Install cfitsio
  vars:
    cfitsio_dir: "{{ astro_dir }}/cfitsio"
    cfitsio_module_dir: "{{ astro_modules }}/cfitsio"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ cfitsio_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/cfitsio{% if not version_number.startswith('3.') %}-{{ version_number }}{% endif %}"
  tags:
    - never
    - cfitsio{{ item.version_number }}
  block:
    - name: Download cfitsio {{ version_number }}
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ astro_src }}/cfitsio-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
        mode: u=rw,g=r,o=r
    - name: Unzip cfitsio {{ version_number }}
      ansible.builtin.unarchive:
        src: "{{ astro_src }}/cfitsio-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"

    - name: Run cfitsio configure {{ version_number }}
      ansible.builtin.command: "./configure --prefix={{ install_dir }}"
      args:
        chdir: "{{ unzipdir }}"

    - name: Build cfitsio {{ version_number }}
      community.general.make:
        chdir: "{{ unzipdir }}"
      environment:
        MAKEFLAGS: "-j {{  ansible_facts['processor_vcpus'] }}"

    - name: Build cfitsio shared {{ version_number }}
      when: "'3.' in version_number"
      community.general.make:
        chdir: "{{ unzipdir }}"
        target: shared
      environment:
        MAKEFLAGS: "-j {{  ansible_facts['processor_vcpus'] }}"

    - name: Install cfitsio {{ version_number }}
      community.general.make:
        chdir: "{{ unzipdir }}"
        target: install

    - name: Install cfitsio module {{ version_number }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ cfitsio_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install cfitsio module file {{ version_number }}
          ansible.builtin.template:
            src: astro/cfitsio.lua
            dest: "{{ cfitsio_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
