- name: Install cfitsio
  vars:
    cfitsio_dir: "{{ astro_dir }}/cfitsio"
    cfitsio_module_dir: "{{ astro_modules }}/cfitsio"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ cfitsio_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/cfitsio{% if not version_number.startswith('3.') %}-{{ version_number }}{% endif %}"
  tags:
    - never
    - cfitsio{{ item.version_number }}
  block:
    - name: Download cfitsio {{ version_number }}
      get_url:
        url: "{{ url }}"
        dest: "{{ astro_src }}/cfitsio-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
    - name: Unzip cfitsio {{ version_number }}
      unarchive:
        src: "{{ astro_src }}/cfitsio-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"

    - name: Run cfitsio {{ version_number }} configure
      command: "./configure --prefix={{ install_dir }}"
      args:
        chdir: "{{ unzipdir }}"

    - name: Build cfitsio {{ version_number }}
      make:
        chdir: "{{ unzipdir }}"
      environment:
        MAKEFLAGS: "-j {{  ansible_processor_vcpus }}"

    - name: Build cfitsio {{ version_number }} shared
      when: "'3.' in version_number"
      make:
        chdir: "{{ unzipdir }}"
        target: shared
      environment:
        MAKEFLAGS: "-j {{  ansible_processor_vcpus }}"

    - name: Install cfitsio {{ version_number }}
      make:
        chdir: "{{ unzipdir }}"
        target: install

    - name: Install cfitsio {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ cfitsio_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install cfitsio {{ version_number }} module file
          template:
            src: astro/cfitsio.lua
            dest: "{{ cfitsio_module_dir }}/{{ version_number }}.lua"
