- name: Install pgplot
  vars:
    pgplot_dir: "{{ astro_dir }}/pgplot"
    pgplot_module_dir: "{{ astro_modules }}/pgplot"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    openmpi_dir: "{{ item.openmpi_dir }}"
    openmpi_module: "{{ item.openmpi_module }}"
    install_dir: "{{ pgplot_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/pgplot-master"
  tags:
    - never
    - pgplot
  block:
    - name: Download pgplot {{ version_number }}
      get_url:
        url: "{{ url }}"
        dest: "{{ astro_src }}/pgplot-{{ version_number }}.zip"
        # checksum: "{{ checksum }}"
    - name: Unzip psrxml {{ version_number }}
      unarchive:
        src: "{{ astro_src }}/pgplot-{{ version_number }}.zip"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"

    # - name: Run pgplot {{ version_number }} bootstrapping
    #   command: "./bootstrap"
    #   args:
    #     chdir: "{{ unzipdir }}"

    # - name: Setup compiler flags and small fixes
    #   command: 'sed -i "s/default(none)//" src/inject_pulsar.c'
    #   args: 
    #     chdir: "{{unzipdir}}"      

    # - name: Run pgplot {{ version_number }} configure
    #   command: "./configure --prefix={{ install_dir }} --with-psrxml-dir={{ psrxml_dir }} --with-fftw-dir={{ fftw_dir }}"
    #   args:        
    #     chdir: "{{ unzipdir }}"
    #   environment: 
    #     CFLAGS: "-I{{ fftw_dir }}/include -fallow-argument-mismatch -fcommon"
    #     FFLAGS: "-I{{ fftw_dir }}/include -fcommon"

    # # WARNINGS:
    # # TODO: LOAD MOST OF THESE SOFTWARE
    # # "configure: WARNING: The PSRFITS code will not be compiled",
    # # "configure: WARNING: PGPLOT code will not be compiled",
    # # "configure: WARNING: Please set the PGPLOT_DIR environment variable",
    # # "configure: WARNING: TEMPO2 code will not be compiled",
    # # "configure: WARNING: Please set the TEMPO2 environment variable",
    # # "configure: WARNING: FFTW code will not be compiled",
    # # "configure: WARNING: FFTW multi-threaded code will not be compiled",
    # # "configure: WARNING: \"No FFTW3 found... you will have to use the slower 'singleton' FFT. Specify location with --with-fftw-dir\"",
    # # "configure: WARNING: \"No TEMPO2 found... Cannot build software that depends on T2toolkit or tempo2\"" 

    # - name: Cleanup pgplot {{ version_number }} before build
    #   make:
    #     target: clean
    #   args: 
    #     chdir: "{{ unzipdir }}"

    # - name: Build pgplot {{ version_number }}
    #   make:
    #     chdir: "{{ unzipdir }}"
    #   environment:
    #     MAKEFLAGS: "-j {{  ansible_processor_vcpus }}"

    # - name: Cleanup pgplot {{ version_number }} after build
    #   make:
    #     target: clean
    #   args: 
    #     chdir: "{{ unzipdir }}"

    # - name: Install pgplot {{ version_number }}
    #   make:
    #     target: install
    #   args:
    #     chdir: "{{ unzipdir }}"

    - name: Install pgplot {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ pgplot_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install pgplot {{ version_number }} module file
          template:
            src: astro/pgplot.lua
            dest: "{{ pgplot_module_dir }}/{{ version_number }}.lua"
