- name: Install sigproc
  # environment:
  #     MAKEFLAGS: "-j {{  ansible_processor_vcpus }}" # todo
  #     FFLAGS: "-fallow-argument-mismatch"  # todo
  #     CC: "gcc-10" # check
  #     FC: "gfortran-10" # check
  vars:
    sigproc_dir: "{{ astro_dir }}/sigproc"
    sigproc_module_dir: "{{ astro_modules }}/sigproc"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    fftw_dir: "{{item.fftw_dir}}",
    psrxml_dir: "{{item.psrxml_dir}}"
    install_dir: "{{ sigproc_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/sigproc-master"
  tags:
    - never
    - sigproc
  block:
    - name: Download sigproc {{ version_number }}
      git:
        repo: https://github.com/SixByNine/sigproc.git
        dest: "{{ unzipdir }}"
        clone: yes
        version: master

    - name: Run sigproc {{ version_number }} bootstrapping
      command: "./bootstrap"
      args:
        chdir: "{{ unzipdir }}"
    - name: Setup compiler flags and small fixes
      command: 'sed -i "s/default(none)//" src/inject_pulsar.c'
      args: 
        chdir: "{{unzipdir}}"      

    - name: Run sigproc {{ version_number }} configure
      command: "./configure --prefix={{ install_dir }} --with-psrxml-dir={{psrxml_dir}} --with-fftw-dir={{fftw_dir}}"
      args:        
        chdir: "{{ unzipdir }}"
      environment: 
        CFLAGS: "-I{{ fftw_dir }}/include -fallow-argument-mismatch -fcommon"
        FFLAGS: "-I{{ fftw_dir }}/include -fcommon"

    - name: Build sigproc {{ version_number }}
      make:
        chdir: "{{ unzipdir }}"
      environment:
        MAKEFLAGS: "-j {{  ansible_processor_vcpus }}"
    - name: Cleanup sigproc {{ version_number }} build directory
      make:
        chdir: "{{ unzipdir }}"
        target: clean
      environment:
        MAKEFLAGS: "-j {{  ansible_processor_vcpus }}"
    - name: Install sigproc {{ version_number }}
      make:
        chdir: "{{ unzipdir }}"
        target: install

    - name: Install sigproc {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ sigproc_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install sigproc {{ version_number }} module file
          template:
            src: astro/sigproc.lua
            dest: "{{ sigproc_module_dir }}/default.lua"
