---
# tasks file for compiled ilifu software

- name: Install usertools
  vars:
    python_dir: "/software/common/python/3.10.1"
    tools:
      - {
          name: "show_cat",
          description: "CLI tool to display images"
      }
  include_tasks:
    file: user_tools.yaml
  tags:
    - never
    - user_tools

- name: Install Disk Management Tools
  vars:
    python_dir: "/software/common/python/3.10.9"
  include_tasks:
    file: disk_management.yaml
  tags:
    - never
    - disk_management

- name: Install MDAnalysis
  vars:
      versions:
      - {
        version_number: "2.5.0",
        python_dir: "/software/common/python/3.10.9",
      }
  include_tasks:
    file: 'mdanalysis.yaml'
  loop: "{{ versions }}"
  tags:
    - never
    - mdanalysis

