- name: Create msPIPE container
  vars:
    checksum: "{{ item.checksum }}"
    container_name: "mspipe"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.{{ item.version_number }}.sif"
    mspipe_module_dir: "{{ bio_modules }}/mspipe"
    tag: "{{ item.tag }}"
    version_number: "{{ item.version_number }}"
  tags:
    - "mspipe{{ item.version_number }}"
    - never
  block:
    - name: Create msPIPE {{ version_number }} container
      block:
        - name: Copy singularity definition file
          template:
              src: "bio/mspipe.def"
              dest: "{{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
        - name: Build singularity container
          command: "{{ singularity }} build {{ container_image }} {{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
          args:
              creates: "{{ container_image }}"
          become: true
          environment:
              SINGULARITY_TMPDIR: "{{ lookup('env','SINGULARITY_TMPDIR') | default('/dev/shm') }}"

    - name: Install msPIPE {{ container_name }} module
      block:
        - name: Check module dir
          file:
            path: "{{ mspipe_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install mspipe module file
          template:
            src: bio/mspipe.lua
            dest: "{{ mspipe_module_dir }}/{{ version_number }}.lua"
