---
- name: Create msPIPE container
  vars:
    checksum: "{{ item.checksum }}"
    container_name: "mspipe"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.{{ item.version_number }}.sif"
    mspipe_binary_dir: "{{ bio_container_dir }}/mspipe/{{ item.version_number }}"
    mspipe_module_dir: "{{ bio_modules }}/mspipe"
    tag: "{{ item.tag }}"
    version_number: "{{ item.version_number }}"
  tags:
    - "mspipe{{ item.version_number }}"
    - never
  block:
    - name: Create msPIPE container {{ version_number }}
      block:
        - name: "Copy singularity definition file to {{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
          ansible.builtin.template:
            src: "bio/mspipe.def"
            dest: "{{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
            mode: u=rw,g=r,o=r
        - name: "Build singularity container {{ container_image }}"
          ansible.builtin.command: "{{ singularity }} build --fakeroot {{ container_image }} {{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
          args:
            creates: "{{ container_image }}"
          environment:
            SINGULARITY_TMPDIR: "{{ lookup('env', 'SINGULARITY_TMPDIR') | default('/dev/shm') }}"
        - name: Ensure mspipe binary directory exists
          ansible.builtin.file:
            path: "{{ mspipe_binary_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Create mspipe binary
          ansible.builtin.template:
            src: "bio/mspipe.sh"
            dest: "{{ mspipe_binary_dir }}/mspipe"
            mode: u=rwx,g=rx,o=rx

    - name: Install msPIPE module {{ container_name }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ mspipe_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install mspipe module file
          ansible.builtin.template:
            src: bio/mspipe.lua
            dest: "{{ mspipe_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
