- name: Create pggb container
  vars:
    checksum: "{{ item.checksum }}"
    container_name: "pggb"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.{{ item.tag }}.sif"
    pggb_module_dir: "{{ bio_modules }}/pggb"
    tag: "{{ item.tag }}"
  tags:
    - "pggb{{ item.tag }}"
    - never
  block:
    - name: Create pggb {{ version_number }} container
      block:
        - name: Copy singularity definition file
          template:
              src: "bio/pggb.def"
              dest: "{{ bio_container_recipe_dir }}/{{ container_name }}.{{ tag }}.def"
        - name: Build singularity container
          command: "{{ singularity }} build {{ container_image }} {{ bio_container_recipe_dir }}/{{ container_name }}.{{ tag }}.def"
          args:
              creates: "{{ container_image }}"
          become: true
          environment:
              SINGULARITY_TMPDIR: "{{ lookup('env','SINGULARITY_TMPDIR') | default('/dev/shm') }}"

    - name: Install pggb {{ container_name }} module
      block:
        - name: Check module dir
          file:
            path: "{{ pggb_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install pggb module file
          template:
            src: bio/pggb.lua
            dest: "{{ pggb_module_dir }}/{{ tag }}.lua"
