---
- name: Create pggb container
  vars:
    checksum: "{{ item.checksum }}"
    container_name: "pggb"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.{{ item.tag }}.sif"
    pggb_module_dir: "{{ bio_modules }}/pggb"
    tag: "{{ item.tag }}"
  tags:
    - "pggb{{ item.tag }}"
    - never
  block:
    - name: Create pggb container {{ version_number }}
      block:
        - name: Copy singularity definition file
          ansible.builtin.template:
            src: "bio/pggb.def"
            dest: "{{ bio_container_recipe_dir }}/{{ container_name }}.{{ tag }}.def"
            mode: u=rw,g=r,o=r
        - name: Build singularity container
          ansible.builtin.command: "{{ singularity }} build --fakeroot {{ container_image }} {{ bio_container_recipe_dir }}/{{ container_name }}.{{ tag }}.def"
          args:
            creates: "{{ container_image }}"
          environment:
            SINGULARITY_TMPDIR: "{{ lookup('env', 'SINGULARITY_TMPDIR') | default('/dev/shm', true) }}"

    - name: Install pggb module {{ container_name }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ pggb_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install pggb module file
          ansible.builtin.template:
            src: bio/pggb.lua
            dest: "{{ pggb_module_dir }}/{{ tag }}.lua"
            mode: u=rw,g=r,o=r
