---
- name: Create snvstory container
  vars:
    container_name: "snvstory"
    container_recipe: "{{ bio_container_recipe_dir }}/{{ container_name }}.def"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.sif"
    snvstory_module_dir: "{{ bio_modules }}/snvstory"
    snvstory_binary_dir: "{{ bio_container_dir }}/snvstory"
  tags:
    - "snvstory"
    - never
  block:
    - name: Copy snvstory recipe  {{ container_recipe }}
      ansible.builtin.template:
        src: "bio/snvstory.def"
        dest: "{{ container_recipe }}"
        mode: u=rw,g=r,o=r
    - name: Git clone snvstory to /dev/shm/snv_story_build
      ansible.builtin.git:
        repo: git@github.com:nch-igm/snvstory.git
        dest: "/dev/shm/snv_story_build"
    - name: Build singularity container
      ansible.builtin.command: "{{ singularity }} build --fakeroot {{ container_image }} {{ container_recipe }}"
      args:
        creates: "{{ container_image }}"
        chdir: "/dev/shm/snv_story_build"
      environment:
        SINGULARITY_TMPDIR: "{{ lookup('env', 'SINGULARITY_TMPDIR') | default('/dev/shm', true) }}"
    - name: Ensure snvstory binary directory exists
      ansible.builtin.file:
        path: "{{ snvstory_binary_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Create snvstory binary
      ansible.builtin.template:
        src: "bio/snvstory.sh"
        dest: "{{ snvstory_binary_dir }}/snvstory"
        mode: u=rwx,g=rx,o=rx

    - name: Install module {{ container_name }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ snvstory_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install snvstory module file
          ansible.builtin.template:
            src: bio/snvstory.lua
            dest: "{{ snvstory_module_dir }}/default.lua"
            mode: u=rw,g=r,o=r
