- name: Create Spectronaut container
  vars:
    base_container_image: "{{ common_container_dir }}/{{ item.base_container_name }}.sif"
    checksum: "{{ item.checksum }}"
    container_name: "spectronaut"
    dotnet_version: "{{ item.dotnet_version | default('8.0') }}"
    spectronaut_version: "{{ item.version_number }}"
    spectronaut_deb_url: "{{ item.deb_url }}"
    spectronaut_deb_file: "{{ bio_src }}/spectronaut_{{ item.version_number }}.deb"
    spectronaut_deb_checksum: "{{ item.checksum }}"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.{{ item.version_number }}.sif"
    spectronaut_binary_dir: "{{ bio_container_dir }}/spectronaut/{{ item.version_number }}"
    spectronaut_module_dir: "{{ bio_modules }}/spectronaut"
    tag: "{{ item.tag }}"
    version_number: "{{ item.version_number }}"
  tags:
    - "spectronaut{{ item.version_number }}"
    - never
  block:
    - name: "Fetch spectronaut {{ spectronaut_version }} deb file"
      get_url:
        url: "{{ spectronaut_deb_url }}"
        dest: "{{ spectronaut_deb_file }}"
        checksum: "{{ spectronaut_deb_checksum }}"
    - name: Create Spectronaut {{ version_number }} container
      block:
        - name: "Copy singularity definition file to {{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
          template:
              src: "bio/spectronaut.def"
              dest: "{{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
        - name: "Build singularity container {{ container_image }}"
          command: "{{ singularity }} build {{ container_image }} {{ bio_container_recipe_dir }}/{{ container_name }}.{{ version_number }}.def"
          args:
              creates: "{{ container_image }}"
          become: true
          environment:
              SINGULARITY_TMPDIR: "{{ lookup('env','SINGULARITY_TMPDIR') | default('/dev/shm') }}"
        - name: Ensure spectronaut binary directory exists
          file:
            path: "{{ spectronaut_binary_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Create spectronaut binary
          template:
            src: "bio/spectronaut.sh"
            dest: "{{ spectronaut_binary_dir }}/spectronaut"
            mode: 0755

    - name: Install Spectronaut {{ container_name }} module
      block:
        - name: Check module dir
          file:
            path: "{{ spectronaut_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install spectronaut module file
          template:
            src: bio/spectronaut.lua
            dest: "{{ spectronaut_module_dir }}/{{ version_number }}.lua"
