---
- name: Create TRIBES container
  vars:
    singularity_sif_url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    version_number: "{{ item.version_number }}"
    container_name: "tribes_{{ version_number }}"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.sif"
    tribes_module_dir: "{{ bio_modules }}/tribes"
    tribes_binary_dir: "{{ bio_container_dir }}/tribes/{{ version_number }}/"
  tags:
    - "TRIBES{{ item.version_number }}"
    - never
  block:
    - name: Create TRIBES container {{ version_number }}
      block:
        - name: Copy TRIBES sif from github {{ version_number }}
          ansible.builtin.get_url:
            url: "{{ singularity_sif_url }}"
            dest: "{{ container_image }}"
            checksum: "{{ checksum }}"
            mode: u=rwx,g=rx,o=rx
        - name: Ensure TRIBES binary directory exists
          ansible.builtin.file:
            path: "{{ tribes_binary_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Create TRIBES binary
          ansible.builtin.template:
            src: "tribes.sh"
            dest: "{{ tribes_binary_dir }}/tribes"
            mode: u=rwx,g=rx,o=rx

    - name: Install TRIBES module {{ container_name }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ tribes_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install TRIBES module file
          ansible.builtin.template:
            src: bio/tribes.lua
            dest: "{{ tribes_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
