---
- name: Create Trycycler container
  vars:
    docker_source: "{{ item.docker_source }}"
    container_name: "trycycler_{{ item.version_name }}.{{ item.version_number }}"
    container_recipe: "{{ bio_container_recipe_dir }}/{{ container_name }}.def"
    container_image: "{{ bio_container_dir }}/{{ container_name }}.sif"
    trycycler_module_dir: "{{ bio_modules }}/trycycler"
    trycycler_binary_dir: "{{ bio_container_dir }}/trycycler/{{ item.version_name }}/{{ item.version_number }}"
  tags:
    - "trycycler.{{ item.version_name }}_{{ item.version_number }}"
    - never
  block:
    - name: Create Trycycler container {{ item.version_number }}
      block:
        - name: Copy recipe  {{ container_recipe }}
          ansible.builtin.template:
            src: "bio/trycycler.def"
            dest: "{{ container_recipe }}"
            mode: u=rw,g=r,o=r
        - name: Build container {{ container_image }}
          ansible.builtin.command: "{{ singularity }} build --fakeroot {{ container_image }} {{ container_recipe }}"
          args:
            creates: "{{ container_image }}"
          environment:
            SINGULARITY_TMPDIR: "{{ lookup('env', 'SINGULARITY_TMPDIR') | default('/dev/shm', true) }}"
        - name: Ensure Trycycler binary directory exists
          ansible.builtin.file:
            path: "{{ trycycler_binary_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Create Trycycler binary
          ansible.builtin.template:
            src: "trycycler.sh"
            dest: "{{ trycycler_binary_dir }}/trycycler"
            mode: u=rwx,g=rx,o=rx

    - name: Install Trycycler module {{ container_name }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ trycycler_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install Trycycler module file
          ansible.builtin.template:
            src: bio/trycycler.lua
            dest: "{{ trycycler_module_dir }}/{{ container_name }}.lua"
            mode: u=rw,g=r,o=r
