---
- name: Create atfncat container
  vars:
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum_sha256 }}"
    base_container_image: "{{ common_container_dir }}/{{ base_container_name }}.sif"
    container_name: "atfncat"
    container_recipe: "{{ astro_container_recipe_dir }}/{{ container_name }}.def"
    container_image: "{{ astro_container_dir }}/{{ container_name }}.sif"
    atfncat_module_dir: "{{ astro_modules }}/atfncat"
    atfncat_binary_dir: "{{ astro_container_dir }}/atfncat"
  tags:
    - "atfncat"
    - never
  block:
    - name: "Check for existence of container {{ base_container_image }}"
      ansible.builtin.stat:
        path: "{{ base_container_image }}"
      register: base_container_exists
    - name: "Missing {{ base_container_image }}"
      ansible.builtin.fail:
        msg: "The container {{ base_container_image }} is missing."
      when: not base_container_exists.stat.exists
    - name: Create atfncat container
      when: base_container_exists.stat.exists
      block:
        - name: Copy atfncat recipe  {{ container_recipe }}
          ansible.builtin.template:
            src: "astro/atfncat.def"
            dest: "{{ container_recipe }}"
            mode: u=rw,g=r,o=r
        - name: Build singularity container
          ansible.builtin.command: "{{ singularity }} build --fakeroot {{ container_image }} {{ container_recipe }}"
          args:
            creates: "{{ container_image }}"
          environment:
            SINGULARITY_TMPDIR: "{{ lookup('env', 'SINGULARITY_TMPDIR') | default('/dev/shm') }}"
        - name: Ensure atfncat binary directory exists
          ansible.builtin.file:
            path: "{{ atfncat_binary_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Create atfncat binary
          ansible.builtin.template:
            src: "atfncat.sh"
            dest: "{{ atfncat_binary_dir }}/psrcat"
            mode: u=rwx,g=rx,o=rx

    - name: Install module {{ container_name }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ atfncat_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install atfncat module file
          ansible.builtin.template:
            src: astro/atfncat.lua
            dest: "{{ atfncat_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
