- name: Install Apache Hadoop
  vars:
    version_number: "{{ item.version_number }}"
    hadoop_dir: "{{ common_dir }}/hadoop"
    hadoop_module_dir: "{{ common_modules }}/hadoop"
    url: "http://apache.is.co.za/hadoop/common/hadoop-{{ version_number }}/hadoop-{{ version_number }}.tar.gz"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ hadoop_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/hadoop-{{ version_number }}"
  tags:
    - never
    - hadoop{{ item.version_number }}
  block:
    - name: Install Apache Hadoop {{ version_number }}
      block:
        - name: Download, compile and install Apache Hadoop {{ version_number }}
          block:
            - name: Download Apache Hadoop {{ version_number }} from {{ url }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/apache-hadoop-{{ version_number }}.tar.tgz"
                checksum: "{{ checksum }}"
            - name: Unzip Apache Hadoop {{ version_number }}
              unarchive:
                src: "{{ common_src }}/apache-hadoop-{{ version_number }}.tar.tgz"
                dest: "/dev/shm"
                creates: "{{ unzipdir }}"
            - name: Ensure Hadoop dir exists
              file:
                path: "{{ hadoop_dir }}"
                state: directory
                mode: u=rwx,g=rwx,o=rx
            - name: Move uncompressed Hadoop {{ version_number }} to {{ install_dir }}
              command: "mv {{ unzipdir }} {{ install_dir }}"
              args:
                creates: "{{ install_dir }}"

#    - name: Install Apache Maven {{ version_number }} module
#      block:
#      - name: Check module dir
#        file:
#          path: "{{ maven_module_dir }}"
#          state: directory
#          mode: u=rwx,g=rwx,o=rx
#      - name: Install Apache Maven {{ version_number }} module file
#        template:
#          src: apache_maven.lua
#          dest: "{{ maven_module_dir }}/{{ version_number }}.lua"
