- name: Install Apache Spark
  vars:
    spark_dir: "{{ common_dir }}/spark"
    spark_module_dir: "{{ common_modules }}/spark"
    url: "http://apache.is.co.za/spark/spark-{{ item.version_number }}/spark-{{ item.version_number }}.tgz"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ spark_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/spark-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - spark{{ item.version_number }}
  block:
    - name: Install Apache Spark {{ version_number }}
      block:
        - name: Download, compile and install Apache Spark {{ version_number }}
          block:
            - name: Download Apache Spark {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/spark-{{ version_number }}.tar.tgz"
                checksum: "{{ checksum }}"
            - name: Unzip Spark {{ version_number }}
              unarchive:
                src: "{{ common_src }}/spark-{{ version_number }}.tar.tgz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
#          - name: Make OpenMPI {{ version_number }} build directory
#            file:
#              path: "{{ build_dir }}"
#              state: directory
#          - name: Run OpenMPI {{ version_number }} configure
#            command: "../configure --prefix={{ install_dir }} --enable-static --with-singularity"
#            args:
#              chdir: "{{ build_dir }}"
#              creates: "{{ build_dir }}/Makefile"
#          - name: Build OpenMPI {{ version_number }}
#            make:
#              chdir: "{{ build_dir }}"
#            environment:
#              MAKEFLAGS: "-j {{ ansible_processor_count }}"
#          - name: Install OpenMPI {{ version_number }}
#            make:
#              chdir: "{{ build_dir }}"
#              target: install
#
#    - name: Install OpenMPI {{ version_number }} module
#      block:
#      - name: Check module dir
#        file:
#          path: "{{ mpi_module_dir }}"
#          state: directory
#          mode: u=rwx,g=rwx,o=rx
#      - name: Install OpenMPI module file
#        template:
#          src: openmpi.lua
#          dest: "{{ mpi_module_dir }}/{{ version_number }}.lua"
