---
- name: "Download {{ the_data.name }} from {{ the_data.url }} to {{ exomiser_data_dir }}"
  tags: [never, exomiser_data]
  get_url:
    url: "{{ the_data.url }}"
    dest: "{{ exomiser_data_dir }}/"
    checksum: "{{ the_data.checksum }}"

- name: "Uncompress {{ the_data.name }}"
  debug:
    msg: "Uncompressing {{ the_data.name }}"