---
- name: Genome Browser and Blat Applications
  vars:
    GenomeBrowser_dir: "{{ bio_dir }}/GenomeBrowser"
    GenomeBrowser_module_dir: "{{ bio_modules }}/GenomeBrowser"
    install_dir: "{{ GenomeBrowser_dir }}"
    GenomeBrowser_url: "{{ url }}"
  tags:
    - never
    - genomebrowser

  block:
    - name: Download, and install GenomeBrowser
      block:
        - name: rsync GenomeBrowser from {{ GenomeBrowser_url }}
          ansible.posix.synchronize:
            src: '{{ GenomeBrowser_url }}'
            dest: '{{ install_dir }}'

    - name: Install GenomeBrowser {{ version_number }} module to {{ GenomeBrowser_module_dir }}
      block:
        - name: Check module dir {{ GenomeBrowser_module_dir }}
          file:
            path: "{{ GenomeBrowser_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install GenomeBrowser module file to {{ GenomeBrowser_module_dir }}/{{ version_number }}.lua
          template:
            src: GenomeBrowser.lua
            dest: "{{ GenomeBrowser_module_dir }}/cli.lua"
