- name: Install GROMACS
  vars:
    gromacs_dir: "{{ bio_dir }}/gromacs"
    gromacs_module_dir: "{{ bio_modules }}/gromacs"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ gromacs_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/gromacs-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
    cuda_root: "{{ item.cuda_root }}"
    cuda_module: "{{ item.cuda_module }}"
    mpi_module: "{{ item.mpi_module }}"
  tags:
    - never
    - gromacs{{ item.version_number }}
  block:
    - name: Install GROMACS {{ version_number }}
      block:
        - name: Download, compile and install GROMACS {{ version_number }}
          block:
            - name: Download GROMACS {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/gromacs-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip GROMACS {{ version_number }}
              unarchive:
                src: "{{ common_src }}/gromacs-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Ensure GROMACS build directory {{ build_dir }} is present
              file:
                path: "{{ build_dir }}"
                state: directory
            - name: Run cmake for GROMACS {{ version_number }}
              command: "cmake .. -DCMAKE_INSTALL_PREFIX:PATH={{ install_dir }} -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_MPI=on -DGMX_GPU=CUDA -DCUDA_TOOLKIT_ROOT_DIR={{ cuda_root }}"
              args:
                chdir: "{{ build_dir }}"
                creates: "{{ build_dir }}/Makefile"
            - name: Build GROMACS {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
                target: "all"
              environment:
                MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
            - name: Install GROMACS {{ version_number }} to {{ install_dir }}
              make:
                chdir: "{{ build_dir }}"
                target: "install"

    - name: Install GROMACS {{ version_number }} module
      block:
        - name: Check GROMACS module dir
          file:
            path: "{{ gromacs_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install GROMACS {{ version_number }} module file
          template:
            src: gromacs.lua
            dest: "{{ gromacs_module_dir }}/{{ version_number }}.lua"
