- name: Install HISAT2
  vars:
    hisat2_dir: "{{ bio_dir }}/hisat2"
    hisat2_module_dir: "{{ bio_modules }}/hisat2"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ hisat2_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/hisat2-{{ version_number }}"
  tags:
    - never
    - hisat2-{{ item.version_number }}
  block:
    - name: Install HISAT2 {{ version_number }}
      block:
        - name: Download and install HISAT2 {{ version_number }}
          block:
            - name: Download HISAT2 {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ bio_src }}/hisat2-{{ version_number }}.zip"
                checksum: "{{ checksum }}"
            - name: Unzip HISAT2 {{ version_number }}
              unarchive:
                src: "{{ bio_src }}/hisat2-{{ version_number }}.zip"
                dest: "/dev/shm"
                creates: "{{ unzipdir }}"
            - name: Ensure hisat2 dir exists
              file:
                  path: "{{ hisat2_dir }}"
                  state: directory
                  mode: u=rwx,g=rx,o=rx
            - name: Move HISAT2 dir from {{ unzipdir }} to {{ install_dir }}
              command:
                cmd: "mv {{ unzipdir }} {{ install_dir }}"
              args:
                creates: "{{ install_dir }}"

    - name: Install HISAT2 {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ hisat2_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install hisat2 module file
          template:
            src: hisat2.lua
            dest: "{{ hisat2_module_dir }}/{{ version_number }}.lua"