---
- name: Install hyphy {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    hyphy_dir: "{{ bio_dir }}/hyphy"
    hyphy_module_dir: "{{ bio_modules }}/hyphy"
    version_number: "{{ item.version_number }}"
    install_dir: "{{ hyphy_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/hyphy-{{ version_number }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
    mpi_dir: "{{ item.mpi_dir }}"
    mpi_module: "{{ item.mpi_module }}"
  tags:
    - never
    - hyphy{{ item.version_number }}

  block:
    - name: Download and install hyphy ({{ version_number }})
      block:
        - name: Download hyphy {{ version_number }} from {{ url }}
          get_url:
            url: "{{ url }}"
            dest: "{{ bio_src }}/hyphy_{{ version_number }}.tar.gz"
            checksum: "{{ checksum }}"
        - name: Unzip source to {{ unzip_dir }}
          unarchive:
            src: "{{ bio_src }}/hyphy_{{ version_number }}.tar.gz"
            dest: "/dev/shm"
            creates: "{{ unzip_dir }}"
        - name: Ensure hyphy dir exists
          file:
            path: "{{ hyphy_dir }}"
            state: directory
            recurse: yes
        - name: Run cmake in {{ unzip_dir }}
          shell: "/usr/bin/cmake ."
          args:
            chdir: "{{ unzip_dir }}/"
            creates: "{{ unzip_dir }}/configure"
          environment:
            PATH: "{{ mpi_dir }}/bin:${PATH}"
            LD_LIBRARY_DIR: "{{ mpi_dir }}/lib:${LD_LIBRARY_DIR}"
            INCLUDE: "{{ mpi_dir }}/include: ${INCLUDE}"
        - name: Make hyphy {{ version_number }} MPI
          make:
            chdir: "{{ unzip_dir }}"
            target: MPI
          environment:
            MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
            PATH: "{{ mpi_dir }}/bin:${PATH}"
            LD_LIBRARY_DIR: "{{ mpi_dir }}/lib:${LD_LIBRARY_DIR}"
            INCLUDE: "{{ mpi_dir }}/include: ${INCLUDE}"
        - name: Install hyphy {{ version_number }}
          make:
            chdir: "{{ unzip_dir }}"
            target: install

#    - name: Install hyphy {{ version_number }} module
#      block:
#        - name: Check module dir {{ hyphy_module_dir }}
#          file:
#            path: "{{ hyphy_module_dir }}"
#            state: directory
#            mode: u=rwx,g=rwx,o=rx
#        - name: Install hyphy {{ version_number }} module file
#          template:
#            src: hyphy.lua
#            dest: "{{ hyphy_module_dir }}/{{ version_number }}.lua"
