---
# tasks file for compiled

- name: Run installs
  tags: always
  ansible.builtin.include_tasks:
    file: "{{ class }}"
  loop:
    - common/main.yml
    - ilifu/main.yml
    - astro/main.yml
    - bio/main.yml
  loop_control:
    loop_var: "class"
