---
# tasks file for compiled

- name: Run installs
  tags: always
  include_tasks:
    file: "{{ class }}"
  loop:
      - common/main.yml
      - ilifu/main.yml
      - astro/main.yml
      - bio/main.yml
  loop_control:
    loop_var: "class"

