- name: Install R
  vars:
    R_dir: "{{ common_dir }}/R"
    R_module_dir: "{{ common_modules }}/R"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ R_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/R-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
    r_packages: '"data.table","devtools","DBI","mgcv","nlme","pacman","rmarkdown","Rcpp","shiny","tidyverse","xtable","biocManager"'
  tags:
    - never
    - R{{ item.version_number }}
  block:
    - name: Install R {{ version_number }}
      block:
        - name: Download, compile and install R {{ version_number }}
          block:
            - name: Download R {{ version_number }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/R-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip R {{ version_number }}
              unarchive:
                src: "{{ common_src }}/R-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Make R {{ version_number }} build directory
              file:
                path: "{{ build_dir }}"
                state: directory
            - name: Run R {{ version_number }} configure
              command: "../configure --prefix={{ install_dir }} --enable-static"
              args:
                chdir: "{{ build_dir }}"
                creates: "{{ build_dir }}/Makefile"
            - name: Build R {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
              environment:
                MAKEFLAGS: "-j {{  ansible_processor_vcpus }}"
            - name: Install R {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
                target: install
            - name: Install R packages {{ r_packages }}
              command: "{{ install_dir }}/bin/Rscript -e 'install.packages(c({{ r_packages }}), repos=\"http://cran.rstudio.com/\")'"
            - name: Ensure Rprofile.site is up-to-date
              lineinfile:
                path: "{{ install_dir }}/lib/R/etc/Rprofile.site"
                create: true
                line: "options(bitmapType='cairo')"
              tags: Rprofile

    - name: Install R {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ R_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install R {{ version_number }} module file
          template:
            src: R.lua
            dest: "{{ R_module_dir }}/{{ version_number }}.lua"
