---
- name: Install seqkit {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    seqkit_dir: "{{ bio_dir }}/seqkit"
    seqkit_module_dir: "{{ bio_modules }}/seqkit"
    version_number: "{{ item.version_number }}"
    install_dir: "{{ seqkit_dir }}/{{ version_number }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
  tags:
    - never
    - seqkit{{ item.version_number }}

  block:
    - name: Download and install seqkit ({{ version_number }})
      block:
        - name: Download seqkit
          get_url:
              url: "{{ url }}"
              dest: "{{ bio_src }}/seqkit.v{{ version_number }}.tar.gz"
              mode: "ug=rwx,o=rx"
              checksum: "{{ checksum }}"
        - name: Ensure installation directory {{ install_dir }} exists
          file:
            path: "{{ install_dir }}"
            state: directory
            recurse: yes

        - name: Uncompress seqkit
          unarchive:
            src: "{{ bio_src }}/seqkit.v{{ version_number }}.tar.gz"
            dest: "{{ install_dir }}"
            remote_src: yes
            creates: "{{ install_dir }}/seqkit"


    - name: Install seqkit {{ version_number }} module
      block:
        - name: Check module dir {{ seqkit_module_dir }}
          file:
            path: "{{ seqkit_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install seqkit {{ version_number }} module file
          template:
            src: seqkit.lua
            dest: "{{ seqkit_module_dir }}/{{ version_number }}.lua"
