- name: Install Slurm DRMAA
  vars:
    drmaa_dir: "{{ common_dir }}/drmaa"
    drmaa_module_dir: "{{ common_modules }}/drmaa"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ drmaa_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/slurm-drmaa-{{ version_number }}"
    build_dir: "{{ unzipdir }}"
  tags:
    - never
    - slurmdrmaa{{ item.version_number }}
  block:
    - name: Install DRMAA for Slurm {{ version_number }}
      block:
        - name: Download, compile and install Slurm for DRMAA {{ version_number }}
          block:
            - name: Download DRMAA for Slurm {{ version_number }} from {{ url }}
              get_url:
                url: "{{ url }}"
                dest: "{{ common_src }}/slurm-drmaa-{{ version_number }}.tar.gz"
                checksum: "{{ checksum }}"
            - name: Unzip DRMAA for Slurm {{ version_number }} to {{ unzipdir }}
              unarchive:
                src: "{{ common_src }}/slurm-drmaa-{{ version_number }}.tar.gz"
                dest: "/dev/shm/"
                creates: "{{ unzipdir }}"
            - name: Check DRMAA for slurm {{ version_number }} build directory
              file:
                path: "{{ build_dir }}"
                state: directory
            - name: Run DRMAA for Slurm {{ version_number }} configure
              command: "./configure --prefix={{ install_dir }}"
              args:
                chdir: "{{ build_dir }}"
                creates: "{{ build_dir }}/Makefile"
            - name: Build DRMAA for Slurm {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
              environment:
                MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
            - name: Install DRMAA for Slurm {{ version_number }}
              make:
                chdir: "{{ build_dir }}"
                target: "install"

    - name: Install DRMAA for Slurm {{ version_number }} module
      block:
        - name: Check module dir {{ drmaa_module_dir }}
          file:
            path: "{{ drmaa_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install DRMAA for Slurm module file {{ mpi_module_dir }}/{{ version_number }}.lua
          template:
            src: slurm-drmaa.lua
            dest: "{{ drmaa_module_dir }}/{{ version_number }}.lua"
