---
- name: Create TensorFlow environment
  vars:
    tensorflow_version: "{{ item.tensorflow_version }}"
    cuda_version: "{{ item.cuda_version }}"
    cudnn_version: "{{ item.cudnn_version }}"
    python_dir: "{{ item.python_dir }}"
    cuda_dir: "{{ item.cuda_dir }}"
    cudnn_dir: "{{ item.cudnn_dir }}"
    tensorflow_dir: "{{ common_dir }}/tensorflow"
    tensorflow_module_dir: "{{ common_modules }}/tensorflow"
    install_dir: "{{ tensorflow_dir }}/{{ tensorflow_version }}_cuda{{ cuda_version }}_cudnn{{ cudnn_version }}"
  tags:
    - never
    - tensorfow{{ item.tensorflow_version }}
  block:
    - name: Ensure installation directory {{ install_dir }} exists
      file:
        path: "{{ install_dir }}/cuda/lib64"
        state: directory
        mode: u=rwx,g=rwx,o=rx
        recurse: yes
    - name: Find cuda files
      find:
        paths: "{{ cuda_dir }}"
        file_type: directory
        recurse: no
        excludes: "lib64"
      register: cuda_files
    - name: Create symbolic links in {{ install_dir }}/cuda
      file:
        src: "{{ filename.path }}"
        dest: "{{ install_dir }}/cuda/{{ filename.path | basename }}"
        state: link
      with_items: "{{ cuda_files.files }}"
      loop_control:
        label: "{{ filename.path | basename }}"
        loop_var: filename
    - name: Find cuda/lib64 files
      find:
          paths: "{{ cuda_dir }}/lib64"
          file_type: any
          recurse: no
      register: cuda_lib64_files
    - name: Create symbolic links for cuda/lib64 files in {{ install_dir }}/cuda/lib64
      file:
          src: "{{ filename.path }}"
          dest: "{{ install_dir }}/cuda/lib64/{{ filename.path | basename }}"
          state: link
      with_items: "{{ cuda_lib64_files.files }}"
      loop_control:
        label: "{{ filename.path | basename }}"
        loop_var: filename



#    - name: Install cudnn {{ version_number }} module to {{ cudnn_module_dir }}
#      block:
#        - name: Check module dir {{ cudnn_module_dir }}
#          file:
#            path: "{{ cudnn_module_dir }}"
#            state: directory
#            mode: u=rwx,g=rwx,o=rx
#        - name: Install cudnn module file to {{ cudnn_module_dir }}/{{ version_number }}.lua
#          template:
#            src: cudnn.lua
#            dest: "{{ cudnn_module_dir }}/{{ version_number }}.lua"
