- name: Install zstd
  vars:
    zstd_dir: "{{ common_dir }}/zstd"
    zstd_module_dir: "{{ common_modules }}/zstd"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ zstd_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/zstd-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
  tags:
    - never
    - zstd{{ item.version_number }}
  block:
    - name: Download zstd {{ version_number }}
      get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/zstd-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
    - name: Unzip zstd {{ version_number }}
      unarchive:
        src: "{{ common_src }}/zstd-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Build zstd {{ version_number }}
      make:
        chdir: "{{ unzipdir }}"
      environment:
        MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
    - name: Install zstd {{ version_number }}
      make:
        chdir: "{{ unzipdir }}"
        target: install
      environment:
        DESTDIR: "{{ install_dir }}"

    - name: Install zstd {{ version_number }} module
      block:
        - name: Check module dir
          file:
            path: "{{ zstd_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install zstd module file
          template:
            src: zstd.lua
            dest: "{{ zstd_module_dir }}/{{ version_number }}.lua"
