---
- name: Install bcbio
  vars:
    bcbio_dir: "{{ bio_dir }}/bcbio"
    bcbio_module_dir: "{{ bio_modules }}/bcbio"
    install_dir: "{{ bcbio_dir }}"
    tools_dir: "{{ install_dir }}/tools"
  tags:
    - never
    - bcbio

  block:
    - name: Download, and install bcbio
      block:
        - name: Download bcbio installer
          ansible.builtin.get_url:
            url: "https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py"
            dest: "{{ bio_src }}/bcbio_nextgen_install.py"
            checksum: "sha256:37709c321b7fa0e66671b5d96683ce6da439adf43992ea199e2fe75dc524dd3e"
            mode: u=rw,g=r,o=r
        - name: Run bcbio installer
          ansible.builtin.command: "python3 {{ bio_src }}/bcbio_nextgen_install.py --genomes hg38 --aligners bwa --aligners hisat2 --aligners minimap2 --tooldir={{
            tools_dir }} --datatarget gemini --isolate {{ install_dir }}"
