---
- name: Install bedtools {{ item.version_number }}
  vars:
    bedtools_dir: "{{ bio_dir }}/bedtools"
    bedtools_module_dir: "{{ bio_modules }}/bedtools"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ bedtools_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/bedtools2-{{ version_number }}"
  tags:
    - never
    - bedtools{{ item.version_number }}

  block:
    - name: Download and install bedtools {{ version_number }}
      block:
        - name: Download bedtools {{ version_number }} from {{ url }}
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{  bio_dir }}/src/bedtools-{{ version_number }}.tar.gz"
            checksum: "{{ checksum }}"
            mode: u=rw,g=r,o=r
        - name: Ensure bedtools dir exists
          ansible.builtin.file:
            path: "{{ install_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Uncompress bedtools to {{ unzip_dir }}
          ansible.builtin.unarchive:
            src: "{{  bio_dir }}/src/bedtools-{{ version_number }}.tar.gz"
            dest: "/dev/shm"
            creates: "{{ unzip_dir }}"
        - name: Make bedtools {{ version_number }}
          community.general.make:
            chdir: "{{ unzip_dir }}"
          environment:
            MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
        - name: Copy bedtools {{ version_number }} binaries to {{ install_dir }}
          ansible.builtin.copy:
            src: "{{ unzip_dir }}/bin/"
            dest: "{{ install_dir }}"
            remote_src: true
            force: true
            mode: preserve

    - name: Install bedtools module {{ version_number }}
      block:
        - name: Check module dir {{ bedtools_module_dir }}
          ansible.builtin.file:
            path: "{{ bedtools_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install bedtools module file {{ version_number }}
          ansible.builtin.template:
            src: bedtools.lua
            dest: "{{ bedtools_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
