---
- name: Install ExpansionHunter {{ item.version_number }}
  vars:
    expansionhunter_dir: "{{ bio_dir }}/expansionhunter"
    expansionhunter_module_dir: "{{ bio_modules }}/expansionhunter"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ expansionhunter_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/ExpansionHunter-v{{ version_number }}-linux_x86_64"
  tags:
    - never
    - expansionhunter{{ item.version_number }}

  block:
    - name: Ensure ExpansionHunter dir exists
      ansible.builtin.file:
        path: "{{ expansionhunter_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Download ExpansionHunter {{ version_number }} from {{ url }}
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ bio_src }}/ExpansionHunter-v{{ version_number }}-linux_x86_64.tar.gz"
        checksum: "{{ checksum }}"
        mode: u=rw,g=r,o=r
    - name: Uncompress ExpansionHunter
      ansible.builtin.unarchive:
        src: "{{ bio_src }}/ExpansionHunter-v{{ version_number }}-linux_x86_64.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzip_dir }}"
    - name: Move unzipped dir to installation location
      ansible.builtin.command: "mv {{ unzip_dir }} {{ install_dir }}"
    - name: Check module dir {{ expansionhunter_module_dir }}
      ansible.builtin.file:
        path: "{{ expansionhunter_module_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Install expansionhunter module file {{ version_number }}
      ansible.builtin.template:
        src: bio/expansionhunter.lua
        dest: "{{ expansionhunter_module_dir }}/{{ version_number }}.lua"
        mode: u=rw,g=r,o=r
