---
- name: Install HAPGEN2
  vars:
    hapgen2_dir: "{{ bio_dir }}/hapgen2"
    hapgen2_module_dir: "{{ bio_modules }}/hapgen2"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ hapgen2_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/hapgen2"
  tags:
    - never
    - hapgen{{ item.version_number }}
  block:
    - name: Download hapgen2 {{ version_number }}
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ bio_src }}/hapgen2_x86_64.{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
        mode: u=rw,g=r,o=r
    - name: Ensure exists {{ install_dir }}
      ansible.builtin.file:
        path: "{{ install_dir }}"
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Unzip hapgen2 {{ version_number }}
      ansible.builtin.unarchive:
        src: "{{ bio_src }}/hapgen2_x86_64.{{ version_number }}.tar.gz"
        dest: "{{ install_dir }}"
        creates: "{{ install_dir }}/hapgen2"

    - name: Install hapgen2 module {{ version_number }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ hapgen2_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install hapgen2 module file {{ version_number }}
          ansible.builtin.template:
            src: bio/hapgen2.lua
            dest: "{{ hapgen2_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
