---
- name: Install libmaus2 {{ item.version_number }}
  vars:
    libmaus2_dir: "{{ bio_dir }}/libmaus2"
    libmaus2_module_dir: "{{ bio_modules }}/libmaus2"
    git_repo: "{{ item.git_repo }}"
    git_tag: "{{ item.git_tag }}"
    version_number: "{{ item.version_number }}"
    install_dir: "{{ libmaus2_dir }}/{{ version_number }}"
    repo_dir: "/dev/shm/libmaus2-{{ version_number }}"
  tags:
    - never
    - libmaus2{{ item.version_number }}

  block:
    - name: Download and install libmaus2 {{ version_number }}
      block:
        - name: git clone libmaus2 repo
          git:
            repo: "{{ git_repo }}"
            dest: "{{  repo_dir }}"
            version: "{{ git_tag }}"
        - name: Ensure libmaus2 dir exists
          file:
            path: "{{ libmaus2_dir }}"
            state: directory
        - name: Run libmaus2 {{ version_number }} configure
          command: "./configure --prefix={{ install_dir }}"
          args:
            chdir: "{{ repo_dir }}"
        - name: Make libmaus2 {{ version_number }}
          make:
            chdir: "{{ repo_dir }}"
          environment:
            MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
        - name: Install libmaus2 {{ version_number }} to {{ install_dir }}
          make:
            chdir: "{{ repo_dir }}"
            target: "install"

#    - name: Install libmaus2 {{ version_number }} module
#      block:
#        - name: Check module dir {{ libmaus2_module_dir }}
#          file:
#            path: "{{ libmaus2_module_dir }}"
#            state: directory
#            mode: u=rwx,g=rwx,o=rx
#        - name: Install libmaus2 {{ version_number }} module file
#          template:
#            src: libmaus2.lua
#            dest: "{{ libmaus2_module_dir }}/{{ version_number }}.lua"
