---
- name: Install LRICAL {{ item.version_number }}
  vars:
    lirical_dir: "{{ bio_dir }}/lirical"
    lirical_module_dir: "{{ bio_modules }}/lirical"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ lirical_dir }}/{{ version_number }}"
    java_module: "{{ item.java_module }}"
    java_directory: "{{ item.java_directory }}"
  tags:
    - never
    - lirical{{ item.version_number }}

  block:
    - name: Download and install LIRICAL {{ version_number }}
      block:
        - name: Ensure LIRICAL dir {{ install_dir }} exists
          file:
            path: "{{ install_dir }}"
            state: directory
            recurse: yes
        - name: Download LIRICAL {{ version_number }} from {{ url }} to {{ install_dir }}/
          get_url:
            url: "{{ url }}"
            dest: "{{ install_dir }}/LIRICAL.jar"
            checksum: "{{ checksum }}"
        - name: Create lirical binary
          template:
            src: lirical.sh.j2
            dest: "{{ install_dir }}/lirical"
            mode: u=rwx,g=rx,o=rx
            force: yes
        - name: Download lirical data files
          command: "{{ java_directory }}/java -jar LIRICAL.jar download"
          args:
            chdir: "{{ install_dir }}"
            creates: "{{ install_dir }}/data"

    - name: Install LIRICAL {{ version_number }} module
      block:
        - name: Check module dir {{ lirical_module_dir }}
          file:
            path: "{{ lirical_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install LIRICAL module file
          template:
            src: lirical.lua
            dest: "{{ lirical_module_dir }}/{{ version_number }}.lua"


