---
- name: Install merqury {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    merqury_dir: "{{ bio_dir }}/merqury"
    merqury_module_dir: "{{ bio_modules }}/merqury"
    version_number: "{{ item.version_number }}"
    install_dir: "{{ merqury_dir }}/merqury-{{ version_number }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
  tags:
    - never
    - merqury{{ item.version_number }}

  block:
    - name: Download and install merqury ({{ version_number }})
      block:
        - name: Download merqury
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ bio_src }}/merqury-v{{ version_number }}.tar.xg"
            mode: "ug=rwx,o=rx"
            checksum: "{{ checksum }}"
        - name: Ensure merqury directory exists {{ install_dir }}
          ansible.builtin.file:
            path: "{{ merqury_dir }}"
            state: directory
            recurse: true

        - name: Uncompress merqury
          ansible.builtin.unarchive:
            src: "{{ bio_src }}/merqury-v{{ version_number }}.tar.xg"
            dest: "{{ merqury_dir }}"
            remote_src: true
            creates: "{{ install_dir }}/merqury.sh"

    - name: Install merqury module {{ version_number }}
      block:
        - name: Check module dir {{ merqury_module_dir }}
          ansible.builtin.file:
            path: "{{ merqury_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install merqury module file {{ version_number }}
          ansible.builtin.template:
            src: merqury.lua
            dest: "{{ merqury_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
