---
- name: Install meryl {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    meryl_dir: "{{ bio_dir }}/meryl"
    meryl_module_dir: "{{ bio_modules }}/meryl"
    version_number: "{{ item.version_number }}"
    install_dir: "{{ meryl_dir }}/meryl-{{ version_number }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
  tags:
    - never
    - meryl{{ item.version_number }}

  block:
    - name: Download and install meryl ({{ version_number }})
      block:
        - name: Download meryl
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ bio_src }}/meryl-{{ version_number }}.Linux-amd64.tar.xz"
            mode: "ug=rwx,o=rx"
            checksum: "{{ checksum }}"
        - name: Ensure meryl directory exists {{ install_dir }}
          ansible.builtin.file:
            path: "{{ meryl_dir }}"
            state: directory
            recurse: true

        - name: Uncompress meryl
          ansible.builtin.unarchive:
            src: "{{ bio_src }}/meryl-{{ version_number }}.Linux-amd64.tar.xz"
            dest: "{{ meryl_dir }}"
            remote_src: true
            creates: "{{ install_dir }}/bin/meryl"

    - name: Install meryl module {{ version_number }}
      block:
        - name: Check module dir {{ meryl_module_dir }}
          ansible.builtin.file:
            path: "{{ meryl_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install meryl module file {{ version_number }}
          ansible.builtin.template:
            src: meryl.lua
            dest: "{{ meryl_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
