---
- name: Install panacus
  vars:
    panacus_dir: "{{ bio_dir }}/panacus"
    panacus_module_dir: "{{ bio_modules }}/panacus"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ panacus_dir }}/{{ item.version_number }}"
    python_location: "{{ item.python_location }}"
    version_number: "{{ item.version_number }}"
    url: "{{ item.url }}"
  tags:
    - never
    - panacus{{ item.version_number }}

  block:
    - name: Create panacus directory
      file:
        path: "{{ panacus_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
    - name: Download panacus
      get_url:
        url: "{{ url }}"
        dest: "{{ bio_src }}/panacus.{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
    - name: Unzip panacus
      unarchive:
        src: "{{ bio_src }}/panacus.{{ version_number }}.tar.gz"
        dest: "/dev/shm"
        creates: "/dev/shm/panacus-{{ version_number }}_x86_64-unknown-linux-musl"
    - name: Move panacus source to install dir
      command: "mv /dev/shm/panacus-{{ version_number }}_x86_64-unknown-linux-musl {{ install_dir }}"
      args:
          creates: "{{ install_dir }}"
    - name: Copy uv files
      copy:
        src: "uv/bio/panacus/0.4.1/{{ uv_file }}"
        dest: "{{ install_dir }}/{{ uv_file }}"
      with_items:
        - "uv.lock"
        - "pyproject.toml"
      loop_control:
        loop_var: uv_file

    - name: Initialise virtual environment
      command: "{{ python_location }}/bin/uv venv"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"

    - name: Synchronise Virtual Environment
      command: "{{ python_location }}/bin/uv sync"
      args:
        chdir: "{{ install_dir }}"


    - name: "Create panacus module directory {{ panacus_module_dir }}"
      file:
          path: "{{ panacus_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install panacus module file"
      template:
        src: bio/panacus.lua
        dest: "{{ panacus_module_dir }}/{{ version_number }}.lua"
