---
- name: Install PLINK {{ item.version_number }}
  vars:
    plink_dir: "{{ bio_dir }}/plink"
    plink_module_dir: "{{ bio_modules }}/plink"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ plink_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/plink-{{ version_number }}"
    build_dir: "{{ unzipdir }}/build"
    plink_url: "{{ item.url }}"
  tags:
    - never
    - plink{{ item.version_number }}

  block:
    - name: Download, compile and install PLINK {{ version_number }}
      block:
        - name: Download PLINK {{ version_number }} from {{ plink_url }}
          ansible.builtin.get_url:
            url: "{{ plink_url }}"
            dest: "{{ bio_src }}/plink2_linux_x86_64.{{ version_number }}.zip"
            checksum: "sha256:{{ checksum }}"
            mode: u=rw,g=r,o=r
        - name: Ensure PLINK directory exists {{ install_dir }}
          ansible.builtin.file:
            path: "{{ install_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Unzip PLINK {{ version_number }}
          ansible.builtin.unarchive:
            src: "{{ bio_src }}/plink2_linux_x86_64.{{ version_number }}.zip"
            dest: "{{ install_dir }}/"
            creates: "{{ install_dir }}/plink2"
    - name: Install plink module {{ version_number }}
      block:
        - name: Check module dir
          ansible.builtin.file:
            path: "{{ plink_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install plink module file
          ansible.builtin.template:
            src: plink.lua
            dest: "{{ plink_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
