---
- name: Install RSEM
  vars:
    RSEM_dir: "{{ bio_dir }}/RSEM"
    RSEM_module_dir: "{{ bio_modules }}/RSEM"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    short_version: "{{ version_number.split('.')[0] }}.{{ version_number.split('.')[1] }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ RSEM_dir }}/{{ version_number }}"
    unzipdir: "/dev/shm/RSEM-{{ version_number }}"
    build_dir: "{{ unzipdir }}"
    r_dir: "{{ item.R_location }}"
    r_module: "{{ item.R_module }}"
  tags:
    - never
    - rsem{{ item.version_number }}
  environment:
    MAKEFLAGS: "-j {{  ansible_facts['processor_vcpus'] }}"
    LD_LIBRARY_PATH: "{{ r_dir }}/lib{% if 'LD_LIBRARY_PATH' in ansible_facts['env'] %}:{{ ansible_facts['env'].LD_LIBRARY_PATH }}{% endif %}"
    LIBRARY_PATH: "{{ r_dir }}/lib{% if 'LIBRARY_PATH' in ansible_facts['env'] %}:{{ ansible_facts['env'].LIBRARY_PATH }}{% endif %}"
    PATH: "{{ r_dir }}/bin{% if 'PATH' in ansible_facts['env'] %}:{{ ansible_facts['env'].PATH }}{% endif %}"
    INCLUDE: "{{ r_dir }}/include{% if 'INCLUDE' in ansible_facts['env'] %}:{{ ansible_facts['env'].INCLUDE }}{% endif %}"
    C_INCLUDE: "{{ r_dir }}/include{% if 'C_INCLUDE' in ansible_facts['env'] %}:{{ ansible_facts['env'].C_INCLUDE }}{% endif %}"
  block:
    - name: Download RSEM {{ version_number }}
      ansible.builtin.get_url:
        url: "{{ url }}"
        dest: "{{ common_src }}/RSEM-{{ version_number }}.tar.gz"
        checksum: "{{ checksum }}"
        mode: u=rw,g=r,o=r
    - name: Unzip RSEM {{ version_number }}
      ansible.builtin.unarchive:
        src: "{{ common_src }}/RSEM-{{ version_number }}.tar.gz"
        dest: "/dev/shm/"
        creates: "{{ unzipdir }}"
    - name: Make RSEM {{ version_number }}
      community.general.make:
        chdir: "{{ build_dir }}"
    - name: Make RSEM ebseq {{ version_number }}
      community.general.make:
        chdir: "{{ build_dir }}"
        target: ebseq
    - name: Ensure exists {{ RSEM_dir }}
      ansible.builtin.file:
        path: "{{ RSEM_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Move RSEM to install directory
      ansible.builtin.command: "mv {{ build_dir }} {{ install_dir }}"
      args:
        creates: "{{ install_dir }}"

    - name: Check module dir
      ansible.builtin.file:
        path: "{{ RSEM_module_dir }}"
        state: directory
        mode: u=rwx,g=rwx,o=rx
    - name: Install RSEM module file {{ version_number }}
      ansible.builtin.template:
        src: bio/RSEM.lua
        dest: "{{ RSEM_module_dir }}/{{ version_number }}.lua"
        mode: u=rw,g=r,o=r
