---
- name: Install seqkit {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    seqkit_dir: "{{ bio_dir }}/seqkit"
    seqkit_module_dir: "{{ bio_modules }}/seqkit"
    version_number: "{{ item.version_number }}"
    install_dir: "{{ seqkit_dir }}/{{ version_number }}"
    url: "{{ item.url }}"
    checksum: "{{ item.checksum }}"
  tags:
    - never
    - seqkit{{ item.version_number }}

  block:
    - name: Download and install seqkit ({{ version_number }})
      block:
        - name: Download seqkit
          ansible.builtin.get_url:
            url: "{{ url }}"
            dest: "{{ bio_src }}/seqkit.v{{ version_number }}.tar.gz"
            mode: "ug=rwx,o=rx"
            checksum: "{{ checksum }}"
        - name: Ensure installation directory exists {{ install_dir }}
          ansible.builtin.file:
            path: "{{ install_dir }}"
            state: directory
            recurse: true

        - name: Uncompress seqkit
          ansible.builtin.unarchive:
            src: "{{ bio_src }}/seqkit.v{{ version_number }}.tar.gz"
            dest: "{{ install_dir }}"
            remote_src: true
            creates: "{{ install_dir }}/seqkit"

    - name: Install seqkit module {{ version_number }}
      block:
        - name: Check module dir {{ seqkit_module_dir }}
          ansible.builtin.file:
            path: "{{ seqkit_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install seqkit module file {{ version_number }}
          ansible.builtin.template:
            src: seqkit.lua
            dest: "{{ seqkit_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
