---
- name: Install smoothxg {{ item.version_number }}
  vars:
    bio_src: "{{ bio_dir }}/src"
    smoothxg_dir: "{{ bio_dir }}/smoothxg"
    smoothxg_module_dir: "{{ bio_modules }}/smoothxg"
    version_number: "{{ item.version_number }}"
    git_commit: "{{ item.git_commit }}"
    install_dir: "{{ smoothxg_dir }}/{{ version_number }}"
    zstd: "{{ item.zstd_dir }}/usr/local"
    zstd_module: "{{ item.zstd_module }}"
    jemalloc: "{{ item.jemalloc_dir }}"
    jemalloc_module: "{{ item.jemalloc_module }}"
  tags:
    - never
    - smoothxg{{ item.version_number }}

  block:
    - name: Download and install smoothxg ({{ version_number }})
      block:
        - name: Clone smoothxg repo
          ansible.builtin.git:
            clone: true
            repo: https://github.com/pangenome/smoothxg.git
            dest: "{{ bio_src }}/smoothxg"
            version: "{{ git_commit }}"
            recursive: true
            force: true
        - name: Run git submodule update
          ansible.builtin.shell: "/usr/bin/git submodule update --init --recursive"
          args:
            chdir: "{{ bio_src }}/smoothxg"

        - name: Ensure smoothxg dir exists
          ansible.builtin.file:
            path: "{{ smoothxg_dir }}"
            state: directory
            recurse: true

        - name: Run cmake
          ansible.builtin.shell: "/usr/bin/cmake -H. -DCMAKE_BUILD_TYPE=Generic -DEXTRA_FLAGS='-march=native -Ofast' -DCMAKE_INSTALL_PREFIX:PATH={{ install_dir }}
            -Bbuild ."
          args:
            chdir: "{{ bio_src }}/smoothxg"
          environment:
            LD_LIBRARY_PATH: "{{ jemalloc }}/lib:{{ zstd }}/lib:{{ ansible_facts['env'].LD_LIBRARY_PATH | default('') }}"
            LIBRARY_PATH: "{{ jemalloc }}/lib:{{ zstd }}/lib:{{ ansible_facts['env'].LD_LIBRARY_PATH | default('') }}"
            INCLUDE: "{{ jemalloc }}/include:{{ zstd }}/include:{{ ansible_facts['env'].INCLUDE | default('') }}"
            C_INCLUDE: "{{ jemalloc }}/include:{{ zstd }}/include:{{ ansible_facts['env'].INCLUDE | default('') }}"
            CPATH: "{{ jemalloc }}/include:{{ zstd }}/include:{{ ansible_facts['env'].INCLUDE | default('') }}"
            PKG_CONFIG_PATH: "{{ jemalloc }}/lib/pkgconfig:{{ zstd }}/lib/pkgconfig:{{ ansible_facts['env'].PKG_CONFIG_PATH | default('') }}"

        - name: Run cmake build
          ansible.builtin.shell: "/usr/bin/cmake --build build -- -j {{ ansible_facts['processor_vcpus'] }}"
          args:
            chdir: "{{ bio_src }}/smoothxg"
          environment:
            LD_LIBRARY_PATH: "{{ jemalloc }}/lib:{{ zstd }}/lib:{{ ansible_facts['env'].LD_LIBRARY_PATH | default('') }}"
            LIBRARY_PATH: "{{ jemalloc }}/lib:{{ zstd }}/lib:{{ ansible_facts['env'].LD_LIBRARY_PATH | default('') }}"
            INCLUDE: "{{ jemalloc }}/include:{{ zstd }}/include:{{ ansible_facts['env'].INCLUDE | default('') }}"
            C_INCLUDE: "{{ jemalloc }}/include:{{ zstd }}/include:{{ ansible_facts['env'].INCLUDE | default('') }}"
            CPATH: "{{ jemalloc }}/include:{{ zstd }}/include:{{ ansible_facts['env'].INCLUDE | default('') }}"
            PKG_CONFIG_PATH: "{{ jemalloc }}/lib/pkgconfig:{{ zstd }}/lib/pkgconfig:{{ ansible_facts['env'].PKG_CONFIG_PATH | default('') }}"
        - name: Copy odgi binary to install dir
          ansible.builtin.copy:
            src: "{{ bio_src }}/smoothxg/deps/odgi/bin/odgi"
            dest: "{{ install_dir }}/bin/odgi"
            mode: u=rwx,g=rwx,o=rx

        - name: Run make install
          community.general.make:
            chdir: "{{ bio_src }}/smoothxg/build"
            target: install

    - name: Install smoothxg module {{ version_number }}
      block:
        - name: Check module dir {{ smoothxg_module_dir }}
          ansible.builtin.file:
            path: "{{ smoothxg_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install smoothxg module file {{ version_number }}
          ansible.builtin.template:
            src: smoothxg.lua
            dest: "{{ smoothxg_module_dir }}/{{ version_number }}.lua"
            mode: u=rw,g=r,o=r
