---
- name: Install stacks {{ item.version_number }}
  vars:
    stacks_dir: "{{ bio_dir }}/stacks"
    stacks_module_dir: "{{ bio_modules }}/stacks"
    url: "{{ item.url }}"
    version_number: "{{ item.version_number }}"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ stacks_dir }}/{{ version_number }}"
    unzip_dir: "/dev/shm/stacks-{{ version_number }}"
  tags:
    - never
    - stacks{{ item.version_number }}

  block:
    - name: Download and install stacks {{ version_number }}
      block:
        - name: Download stacks {{ version_number }} from {{ url }}
          get_url:
            url: "{{ url }}"
            dest: "{{ bio_dir }}/src/stacks-{{ version_number }}.tar.gz"
            checksum: "{{ checksum }}"
        - name: Ensure stacks dir exists
          file:
            path: "{{ stacks_dir }}"
            state: directory
        - name: Uncompress stacks to {{ unzip_dir }}
          unarchive:
            src: "{{ bio_dir }}/src/stacks-{{ version_number }}.tar.gz"
            dest: "/dev/shm"
            creates: "{{ unzip_dir }}"
        - name: Run stacks {{ version_number }} configure
          command: "./configure --prefix={{ install_dir }}"
          args:
            chdir: "{{ unzip_dir }}"
            creates: "{{ unzip_dir }}/Makefile"
        - name: Make stacks {{ version_number }}
          make:
            chdir: "{{ unzip_dir }}"
          environment:
            MAKEFLAGS: "-j {{ ansible_processor_vcpus }}"
        - name: Install stacks {{ version_number }} to {{ install_dir }}
          make:
            chdir: "{{ unzip_dir }}"
            target: "install"

    - name: Install stacks {{ version_number }} module
      block:
        - name: Check module dir {{ stacks_module_dir }}
          file:
            path: "{{ stacks_module_dir }}"
            state: directory
            mode: u=rwx,g=rwx,o=rx
        - name: Install stacks {{ version_number }} module file
          template:
            src: stacks.lua
            dest: "{{ stacks_module_dir }}/{{ version_number }}.lua"
