---
- name: Install WhatsHap
  vars:
    whatshap_dir: "{{ bio_dir }}/whatshap"
    whatshap_module_dir: "{{ bio_modules }}/whatshap"
    checksum: "{{ item.checksum }}"
    install_dir: "{{ whatshap_dir }}/{{ item.version_number }}"
    python_location: "{{ item.python_location }}"
    version_number: "{{ item.version_number }}"
    pipfile_prefix: "Pipfiles/whatshap.{{ version_number }}"
  tags:
    - never
    - whatshap{{ item.version_number }}

  block:
    - name: Ensure WhatsHap {{ version_number }} directory exists
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: "ug=rwx,o=rx"
        recurse: yes
    - name: Copy Pipfiles
      copy:
        src: "{{ pipfiles.src }}"
        dest: "{{ pipfiles.dest }}"
      with_items:
        - {
            src: "{{ pipfile_prefix }}.Pipfile",
            dest: "{{ install_dir }}/Pipfile"
          }
        - {
            src: "{{ pipfile_prefix }}.Pipfile.lock",
            dest: "{{ install_dir }}/Pipfile.lock"
          }
      loop_control:
        loop_var: pipfiles

    - name: Create Virtual Environment
      command: "{{ python_location }}/bin/pipenv sync"
      args:
        chdir: "{{ install_dir }}"
        creates: "{{ install_dir }}/.venv"
      environment:
        PIPENV_VENV_IN_PROJECT: "1"
        PIPENV_IGNORE_VIRTUALENVS: "1"


    - name: "Create WhatsHap module directory {{ whatshap_module_dir }}"
      file:
          path: "{{ whatshap_module_dir }}"
          state: directory
          mode: "ug=rwx,o=rx"
    - name: "Install WhatsHap module file"
      template:
        src: bio/whatshap.lua
        dest: "{{ whatshap_module_dir }}/{{ version_number }}.lua"
