---
- name: Import all playbook
  hosts: all
  become: false
  roles:
    - all

- name: Import compiled playbook
  become: false
  hosts: all
  roles:
    - compiled

- name: Import containers playbook
  become: false
  hosts: all
  roles:
    - containers
  environment:
    SINGULARITY_TMPDIR: "{{ lookup('env','SINGULARITY_TMPDIR') | default('/dev/shm') }}"
